# Use the official Node.js image.
FROM node:18

# Set the working directory inside the container.
WORKDIR /app

# Copy package.json and package-lock.json to the working directory.
COPY package*.json ./

# Install dependencies.
RUN npm install

# Copy backend code.
COPY backend ./backend

# Expose backend port.
EXPOSE 5000

# Start the backend server.
CMD ["npm", "run", "server"]
